@startuml
'https://plantuml.com/class-diagram

class Converter {
    site_path : Path
    convert()
}

class ConvertArticles
Converter <|-- ConvertArticles

class ConvertForum
Converter <|-- ConvertForum

class ConvertDownloads
Converter <|-- ConvertDownloads

class ConvertGalleries
Converter <|-- ConvertGalleries

@enduml
