@startuml
'https://plantuml.com/class-diagram

class Converter

class MakePage {
    ref_to: Converter
    make()
}
MakePage .> Converter : "uses"

class MakeHomePage
MakePage <|-- MakeHomePage

class MakeAssociationPage
MakePage <|-- MakeAssociationPage

class MakeBlogLinksPage
MakePage <|-- MakeBlogLinksPage

@enduml
